line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "W", "B", "RUF"]
ignore = [
    "E501",
    "RUF001",
    "RUF002",
    "RUF012",
    "RUF022",
    "B015",
]

[format]
quote-style = "double"
indent-style = "space"
